config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, :only => [:create, :edit]
  resources :emails
  resources :organisations do
    resources :groups, :only => [:index]
    resources :contacts, :only => [:index]
  end
  resources :contacts
  get '/mailer', :to => 'application#mailer', :as => 'mailer'
  post '/sendmail', :to => 'application#sendmail', :as => 'sendmail'

  root :to => 'application#index'

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :contacts
  has_many :organisation_relations
  has_many :groups, :through => :organisation_relations

  validates_presence_of :name
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to root_path, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { redirect_to root_path, notice: @organisation.errors }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to root_path, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { redirect_to root_path, notice: @organisation.errors }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:name, :group_ids => [])
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.haml
= simple_form_for(@organisation) do |f|
  -#- if @organisation.errors.any?
  = f.input :name
  = f.association :groups
  .form-group
    = f.submit nil, :class => 'btn btn-success'
-#<%= form_for(@organisation) do |f| %>
-#  <% if @organisation.errors.any? %>
-#    <div id="error_explanation">
-#      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>
-#
-#      <ul>
-#      <% @organisation.errors.full_messages.each do |message| %>
-#        <li><%= message %></li>
-#      <% end %>
-#      </ul>
-#    </div>
-#  <% end %>
-#
-#  <div class="field">
-#    <%= f.label :name %><br>
-#    <%= f.text_field :name %>
-#  </div>
-#  <div class="actions">
-#    <%= f.submit %>
-#  </div>
-#<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.haml
.col-md-12
  %h2 Список организаций
  %table.table.table-hover.table-striped
    %thead
      %tr
        %td{:colspan => 2}
    %tbody
      - @organisations.each do |organisation|
        %tr
          %td= link_to organisation.name, organisation_path(organisation)
          %td
            \Контактов:
            = organisation.contacts.count
  = link_to 'Вернуться', root_path

app/views/organisations/new.haml
.col-md-12
  %h2 Новая организация
  = render 'form'
  = link_to 'Вернуться', root_path

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>