config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, :only => [:create, :edit]
  resources :emails
  resources :organisations do
    resources :groups, :only => [:index]
    resources :contacts, :only => [:index]
  end
  resources :contacts
  get '/mailer', :to => 'application#mailer', :as => 'mailer'
  post '/sendmail', :to => 'application#sendmail', :as => 'sendmail'

  root :to => 'application#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :relations
  has_many :contacts, :through => :relations
  has_many :organisation_relations
  has_many :organisations, :through => :organisation_relations

  validates_presence_of :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    if params[:organisation_id].nil?
      @groups = Group.all
    else
      @organisations = Organisation.find(params[:organisation_id].split(','))
      @groups = []
      @organisations.each do |org|
        @groups.concat org.groups
      end
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @group }
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, :notice => 'Group was successfully created.' }
        format.json { render :show, :status => :created, :location => @group }
      else
        format.html { redirect_to root_path, :notice => @group.errors }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :organisation_ids => [], :contact_ids => [])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.haml
= simple_form_for(@group) do |f|
  = f.input :name
  = f.association :organisations, include_blank: true
  = f.association :contacts, include_blank: true

  .form-group
    = f.submit nil, :class => 'btn btn-success'

app/views/groups/edit.haml
.col-md-12
  %h2
    = @group.name
    \ :: Редактирование
  = render 'form'
  = link_to 'Просмотреть', group_path(@group)
  = link_to 'Вернуться', root_path

app/views/groups/index.haml
.col-md-12
  %h2 Список отделов
  %table.table.table-hover.table-striped
    %thead
      %tr
        %td{:colspan => 2}
    %tbody
      - @groups.each do |group|
        %tr
          %td= link_to group.name, group_path(group)
          %td
            \Контакты:
            = group.contacts.count
  = link_to 'Вернуться', root_path

app/views/groups/new.haml
.col-md-12
  %h2 Новый отдел
  = render 'form'
  = link_to 'Вернуться', root_path

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>