config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, :only => [:create, :edit]
  resources :emails
  resources :organisations do
    resources :groups, :only => [:index]
    resources :contacts, :only => [:index]
  end
  resources :contacts
  get '/mailer', :to => 'application#mailer', :as => 'mailer'
  post '/sendmail', :to => 'application#sendmail', :as => 'sendmail'

  root :to => 'application#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :organisation
  has_many :emails
  has_many :relations
  has_many :groups, :through => :relations

  validates_presence_of :name, :email
  validates :email, :email => true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /contacts
  # GET /contacts.json
  def index
    logger.debug params
    if params[:group_by].nil?
      @contacts = Contact.all
    elsif params[:group_by].present?
      if params[:group_by] == 'group'
        @contacts = {
            :contacts => Relation.joins(:contact, :group).select('"relations"."contact_id", "relations"."group_id", "contacts"."name", "contacts"."email"'),
            :groups => Group.all
        }
      elsif params[:group_by] == 'organisation'
        @contacts = {
            :contacts => Contact.select(:id, :organisation_id, :name).all,
            :organisations => Organisation.select(:id, :name).all
        }
      end
    elsif params[:organisation_id].present?
      @organisations = Organisation.find(params[:organisation_id].split(','))
      @contacts = []
      @organisations.each do |org|
        @contacts.concat org.contacts
      end
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { redirect_to root_path, notice: @contact.errors }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to root_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { redirect_to root_path, notice: @contact.errors }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :email, :organisation_id, :group_ids => [])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.haml
= simple_form_for(@contact) do |f|
  = f.input :name
  = f.association :organisation, include_blank: true
  = f.association :groups, include_blank: true
  .form-group
    = f.submit nil, :class => 'btn btn-success'

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.haml
.col-md-12
  %h2 Список персон
  %table.table.table-hover.table-striped
    %thead
      %tr
        %td{:colspan => 4}
    %tbody
      - @contacts.each do |contact|
        %tr
          %td= link_to contact.name, contact_path(contact)
          %td
            \Организация:
            = link_to contact.organisation.name, organisation_path(contact.organisation) unless contact.organisation.nil?
          %td
            \Отделы:
            - contact.groups.each do |group|
              = link_to group.name, group_path(group)
          %td
            \Адреса:
            - contact.emails.each do |email|
              = link_to email.email, email_path(email)
  = link_to 'Вернуться', root_path

app/views/contacts/new.haml
.col-md-12
  %h2 Новый контакт
  = render 'form'
  = link_to 'Вернуться', root_path

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>