config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, :only => [:create, :edit]
  resources :emails
  resources :organisations do
    resources :groups, :only => [:index]
    resources :contacts, :only => [:index]
  end
  resources :contacts
  get '/mailer', :to => 'application#mailer', :as => 'mailer'
  post '/sendmail', :to => 'application#sendmail', :as => 'sendmail'

  root :to => 'application#index'

end

app/views/layouts/application.haml
-#<!DOCTYPE html>
-#<html>
-#<head>
-#  <title>Mailer</title>
-#  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
-#  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
-#  <%= csrf_meta_tags %>
-#</head>
-#<body>
-#
-#<%= yield %>
-#
-#</body>
-#</html>
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge'}
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %title Почтовик
    = stylesheet_link_tag 'application', :media => :all
    = csrf_meta_tags
  %body
    .container
      .col-md-12
        .row
          %nav.navbar.navbar-default
            .container-fluid
              .navbar-header
                = link_to 'Главная', root_path, :class => 'navbar-brand'
              - if user_signed_in?
                %ul.nav.navbar-nav.navbar-right
                  %li= link_to current_user.email, '#'
                  %li= link_to 'Выйти', destroy_user_session_path, :method => :delete
    .container
      .row
        - if action_name != 'mailer' and user_signed_in?
          .col-md-4.col-md-offset-4
            = link_to mailer_path, :class => 'btn btn-info btn-block' do
              %span.glyphicon.glyphicon-envelope
              \Перейти к отправке
          .clearfix
        = yield
    = javascript_include_tag 'application'